NFS_CORE_PARAM {
    nb_worker = 4;
    Protocols = 3, 4;
    NFS_Port = 2049;
    MNT_Port = 20048;
    NLM_Port = 32803;
    Rquota_Port = 875;
    Mount_Path_Pseudo = true;
}

NFSv4 {
    RecoveryBackend = "null";
    Minor_Versions = 0, 1, 2;
}

EXPORT {
    Export_Id = 77;
    Path = /data/repository;
    Pseudo = /export;
    Access_Type = RO;
    Squash = No_Root_Squash;
    PrivilegedPort = false;
    Protocols = 3, 4;
    Transports = TCP, UDP;
    SecType = sys;

    FSAL {
        Name = VFS;
    }
}

LOG {
    Default_Log_Level = INFO;
    Facility {
        name = FILE;
        destination = "/data/scratch/ganesha.log";
        enable = active;
    }
}
